---
  - hosts: all
    become_method: sudo
    become_user: root
    vars:
      mac_user: jamin
      full_name: "Jamin Ragle"
      email_addr: jragle@mrn.org
      github_username: zombieprocess
      dotfiles_repo: "https://github.com/{{github_username}}/dotfiles"
      home_dir: "/Users/{{mac_user}}"
      dotfiles_dir: "{{home_dir}}/dotfiles"
    tasks:
      - include: tasks/macos_customization.yml tags=macos
      #- include: tasks/dotfiles.yml tags=dotfiles
      - include: tasks/pip.yml tags=pip
      - include: tasks/homebrew.yml tags=homebrew
      - include: tasks/apm.yml tags=apm
      # - include: tasks/npm.yml tags=npm
