---
  # Atom package manager (apm) packages
  - name: Install apm packages
    shell: apm install {{ item }}
    args:
      creates: "{{ home_dir }}/.atom/packages/{{ item }}/"
    with_items: apm_packages
